services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  django:
    build:
      context: .
    container_name: django
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./cv_tracker:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A cv_tracker.celery worker --loglevel=info
    volumes:
      - ./cv_tracker:/app
    working_dir: /app
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A cv_tracker.celery beat --loglevel=info
    volumes:
      - ./cv_tracker:/app
    working_dir: /app
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
