# Generated by Django 6.0.1 on 2026-01-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
