# Generated by Django 6.0.1 on 2026-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_alter_joboffer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('NEW', 'NOWE'), ('CHECKED', 'SPRAWDZONE'), ('SENT', 'WYSŁANO CV')], default='NEW', max_length=10),
        ),
    ]
